### ISSUE TITLE
Suggestion: use `onepasswordDocument` to simplify `~/.ssh/config`

### ISSUE THREAD

**Issue by twpayne** [marcus-crane/dotfiles#7]
Hi, I saw [your tweet](https://twitter.com/sentreh/status/1450243542870228993) about using 1Password and specifically these lines:

https://github.com/marcus-crane/dotfiles/blob/main/dot_ssh/config.tmpl#L12-L16

chezmoi has a [`onepasswordDocument` template function](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#onepassworddocument-uuid-vault-uuid-account-name) which [I use](https://github.com/twpayne/dotfiles/blob/master/private_dot_ssh/config.tmpl#L47) and might allow you to simplify your code. In my case, I keep my work-specific SSH config in a 1Password Document and insert it into `~/.ssh/config` directly.

Hope this helps, and of course close the issue if it's not relevant.

**Comment by marcus-crane** [comment]
Ah, thanks for the suggestion 🙂 In this case, we have an internal repo with some config already built out. I think I probably will just copy and paste it to simplify caching but the idea was that it'd be possible to "invalidate" my config and pull any new updates. I do think the overhead of having to do `eval $(op blah)` every time I refresh my work config isn't work it though.
